### ISSUE TITLE
[feature request] keyboard shortcut for top 1 launch

### ISSUE THREAD

**Issue by paulvi** [pedrosans/launcher-extension#4]
It would be nice to have a keyboard shortcut for 1st (and someone may like 2nd, 3rd) launch.

**Comment by pedrosans** [comment]
Hi @paulvi , the plugin already maps F12 to the 'Launch Preferred Configuration' command, the same command executed by the heart button in the toolbar. This mapping can also be tweaked in the ```General > Key``` page in the Preferences window.

**Comment by paulvi** [comment]
already in README.

closing
